js/build.js
We should send the password to get the user.
The data source won't send us the password when getting just by email.
=> Get user with email/pass

js/interface.js
https://github.com/fliplet/fliplet-studio/issues/1123
=> Ensures datasources is an array

widget.json
Fixes: Fliplet/fliplet-studio/issues/1240
=> Fix: Datasource reference

js/build.js
This fixes the height when errors appear by calculating the height again.
=> Fixes height of state when errors appear

js/interface.js
https://sentry.io/fliplet/widgets-interface/issues/363116979/
=> Fix: when there's no current data source

js/build.js
https://github.com/Fliplet/fliplet-studio/issues/1592
=> Disables password autofill in edit mode

js/build.js
ref https://github.com/Fliplet/fliplet-studio/issues/1753
=> Rely on session to redirect instead of local storage

css/build.css
So many unnecessary styles here. I'm removing the one that's clashing with Fliplet login at the moment. This still needs to be cleaned up.
Also, untabify
=> Removes style for .form-control[disabled]

js/build.js
A [previous PR](https://github.com/Fliplet/fliplet-widget-login-data-source/pull/31) only added user profiles for new logins.
This PR adds user profile information for cached logins as well.
It also fixes an issue where cached logins weren't correctly redirecting users because redirection used to use `data.action` when it should be using `data.loginAction` for `Fliplet.Navigate.to()`
=> Ensure user profiles are added for cached logins

js/build.js
Deals with the following [reported issue](https://docs.google.com/spreadsheets/d/1ITLCZm9fg_A-LIYQDbJsNyTWqPFyF0_25F6-cIR9Z84/edit):
> - fliplet login (probably login) - 'forgot password' not tracked
Also adjusted some coding pattern. Tested and verified login and forgot password features are working.
=> Tracks login success/fail and forgot password

js/build.js
```js
Fliplet.Hooks.on('login', function (data) {
// data contains passport, session, entry, userProfile
});
```
Sample of the `data`:
=> New hook to be fired when logging in

js/interface.js
Needs Ref. https://github.com/Fliplet/fliplet-api/pull/3033
Fixes:
Ref. https://github.com/Fliplet/fliplet-studio/issues/3604
Ref. https://github.com/Fliplet/fliplet-studio/issues/3601
=> Login component will now pass the appId when getting a datasources

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/3418
Basically, I maintain a temp key-value store of the email/password columns so they are not lost after the data source emits an event.
=> Fixed email and password columns

build.html, css/build.css, js/build.js
Ref.
- https://github.com/Fliplet/fliplet-studio/issues/4005
- https://github.com/Fliplet/fliplet-studio/issues/3838
Usability also improved through:
- Making fields taller and more consistent with other input fields in Fliplet apps
- Allows form submission through ENTER
- Disables autocomplete
=> Improves usability for login and forgot password forms

build.html, js/build.js
Ref.
- https://github.com/Fliplet/fliplet-studio/issues/3838
- https://github.com/Fliplet/fliplet-studio/issues/4026
- https://github.com/Fliplet/fliplet-studio/issues/4029
=> Fixes flow for resetting password

js/build.js
ref https://github.com/Fliplet/fliplet-studio/issues/4082
---
- Allow password to be reset when the email case does not match
- Make sure we don't tell the user the password has been updated in case of "non affected rows"
=> improvements for resetting the password

build.html, css/build.css, js/build.js, js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/4082 and other issues reported as part of the LMA app testing, including:
1. Form fields should have the box shadow and inset shadow removed
1. Email verification button doesn't reset when an error occurs
1. Component settings fail to save when a data source isn't selected
=> Fixes login form styles, interaction and form issues

build.html
Ref. https://github.com/Fliplet/fliplet-studio/issues/4124
=> Adds h1 heading back

js/interface.js
requires ref https://github.com/Fliplet/fliplet-api/pull/3276
=> Automatically update dataSource definition to remove password column from being sent

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/3681
=> Prevents errors where forEach is executed on undefined variables

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/3685
=> Fix error with undeclared variable

js/interface.js
@squallstar @tonytlwu 
Fixed behavior:
When creating a data source from the login component, console error is generated.
Corrected variable name.
ref https://github.com/Fliplet/fliplet-studio/issues/4698
=> Data source login error

js/interface.js
@tonytlwu @squallstar 
Fliplet/fliplet-studio#4891
Now if values in email and password fields are undefined, they set to value 'none'.
=> "Email field" & "Password field" now not empty when dropping the Login component

interface.html, js/interface.js
@tonytlwu @squallstar
Issue
Fliplet/fliplet-studio#4959
Description
Added link on "Need help" button. Removed not needed function.
Backward compatibility
=> Clicking on "Need help" now leads to Fliplet documentation about Login components

js/build.js
@tonytlwu @squallstar 
https://github.com/Fliplet/fliplet-studio/issues/4427
Change toast message for one which will fit the modal
(Upload screenshots or screencasts as relevant)
=> Change toast message for one which will fit the modal

css/build.css
https://github.com/Fliplet/fliplet-studio/issues/5366
Added min-width according to Tony's comment.
We cannot reproduce the issue as we dont have access to flipltionian app. 
=> Reset button now is not cropped on desktop 

js/interface.js
Fliplet/fliplet-studio#5642
Updated default prompt to Fliplet prompt.
=> Updated prompt modal

.eslintrc, .gitignore, js/build.js, js/interface.js, package-lock.json
Added eslint.
Fixed eslint errors.
=> Adding eslint

js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/5740
=> fixes strict comparison number-number

js/build.js
https://github.com/Fliplet/fliplet-studio/issues/5354
Change widget inits to Fliplet.Widget.instance
=> Change widget inits to Fliplet.Widget.instance

js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/6003
=> allow email template to be modified

interface.html
Ref. https://github.com/Fliplet/fliplet-studio/issues/6069
=> Fixes typo

css/interface.css, interface.html, js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/6071
The default expiration time will be set to 2 days.
=> Added possibility to change email verification expiration time for login component

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5662
Fixed styles assignment when selecting a data source. 
=> Data source selection now works correctly

js/build.js
https://github.com/Fliplet/fliplet-studio/issues/6095
The issue occurred due to incorrect jquery selectors.
https://streamable.com/wa4xvq
@upplabs-alex-levchenko @YaroslavOvdii
=> Error now display correctly on Login components

build.html, css/build.css, js/build.js
@sofiiakvasnevska
https://github.com/Fliplet/fliplet-studio/issues/6421
Added possibility to tab to 'Forgot password' and 'Back to login' buttons.
Event on them will be triggered either by click, space and enter.
Focused buttons will be dark blue color.
https://streamable.com/nu9dsw
=> [Feature] Added possibility to tab 'Forgot password' and 'Back' buttons

build.html, css/build.css
@sofiiakvasnevska
https://github.com/Fliplet/fliplet-studio/issues/6421
Added class outline-item-selector to all elements that need to be highlighted. 
https://streamable.com/kmhmrd
=> [Fix] Accessibility improvements

interface.html, js/interface.js, widget.json
OD-12 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-12
Integration DS Provider: Login
https://screencast-o-matic.com/watch/cY61VOKue7
=> OD-12 [Feature] DS Provider login integration

js/build.js
OD-182 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-182
Fix to bug in login process
https://screencast-o-matic.com/watch/cY6Q65KduV
=> OD-182 [BUG] Error message i shown when user tries to login

js/build.js, js/interface.js
OD-204 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-204
Remove wrong variable
=> OD-204 [BUG] Login is using wrong variable to connect with data source

css/interface.css, interface.html
OD-187 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-187
Change need help link
https://screencast-o-matic.com/watch/cY6OIxs2w9
@YaroslavOvdii
=> OD-187 [Feature] Change to Need help link

js/build.js
@sofiiakvasnevska
OD-320 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-320
Added input parameter to `back-login` function. 
Because of this, the function did not work because the condition was not met
https://screencast-o-matic.com/watch/crVj22PUDn
=> OD-320 [Fix] Login component button Login is not working after reset password

interface.html
OD-328 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-328
- Remove `ui-sortable` class
=> OD-328 [Feature] Remove a workaround from all the components using DS provider

interface.html
Ref. https://weboo.atlassian.net/browse/ID-1128
Fixes the issue as shown in https://jsfiddle.net/tonytlwu/m29b8eqt/
=> ID-1128 [Fix] Fix collapsed email template

js/build.js
Ref. https://weboo.atlassian.net/browse/ID-1072
=> ID-1072 [Feat] Show error messages as returned by API

js/build.js
@romanyosyfiv
OD-369 https://weboo.atlassian.net/browse/OD-369
The text of the message has been replaced with the correct one
=> OD-369 [Fix] Fixed login message when security is disabled in Studio

js/build.js
Ref. https://weboo.atlassian.net/browse/ID-2277
=> ID-2303 [Fix] Wait for framework initialization before initializing component

js/build.js
Ref. https://weboo.atlassian.net/browse/ID-2348
=> ID-2348 [Fix] Rescope userDataPV and other variables to prevent scope issues

build.html, css/build.css, js/build.js
@romanyosyfiv @inna-bieshulia
OD-790 https://weboo.atlassian.net/browse/OD-790
Added password complexity options to Reset Password field
Added 5 complexity options:
- Uppercase characters
- Lowercase characters
- Numeric characters
- Non-alphanumeric characters or symbols
- Minimum length
//www.awesomescreenshot.com/video/9041684?key=f17b1bef5bd4d04ba485759c53f3aae8
=> OD-790 [Feature] Added password complexity options to Reset Password field

js/build.js, js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-2620
=> ID-2620 [Fix] Update password reset UI on error

js/build.js, js/interface.js
See changes without whitespaces as the indentation got changed a little following my changes.
I refactored the reset password feature to use a new dedicated endpoint.
=> ID-2621 [Feat] Refactor for password reset to use new endpoint

css/interface.css, interface.html, js/build.js, js/interface.js
**Product areas affected**
Login Component
**What does this PR do?**
implemented the logout x period of time functionality for the login component
**JIRA ticket**
[click here](https://weboo.atlassian.net/browse/XOR-665)
**Result**
**Checklist**
None
**Testing instructions**
None
**Deployment instructions**
None
**Author concerns**
None
=> XOR-665 [FEAT] Logout x period of time

build.html
Ref. https://weboo.atlassian.net/browse/ID-2777
=> ID-2777 [Fix] Fixes issue where message for incorrect email is not translated correctly

build.html, css/interface.css, interface.html, js/build.js, js/interface.js
| PR | Merged by |
| -- | --------- |
| #111 ID-2620 [Fix] Update password reset UI on error |  @tonytlwu |
| #113 ID-2621 [Feat] Refactor for password reset to use new endpoint |  @squallstar |
| XOR-665 [FEAT] Logout x period of time #114 |  @amolsuryawanshi4 |
| ID-2777 [Fix] Fixes issue where message for incorrect email is not translated correctly #115 |  @tonytlwu |
=> Release to Production

js/build.js
Ref. https://weboo.atlassian.net/browse/ID-2840
=> ID-2840 [Fix] Run a new hook when sessions are validated

build.html, css/interface.css, interface.html, js/build.js, js/interface.js, translation.json, widget.json
Force registration screen to be set up on Free and Public apps
https://weboo.atlassian.net/browse/ID-4531
=> ID-4531 Force registration screen to be set up on Free and Public apps

build.html, css/interface.css, interface.html, js/build.js, js/interface.js, translation.json, widget.json
Force registration screen to be set up on Free and Public apps
https://weboo.atlassian.net/browse/ID-4531
=> Release 20240704

build.html, css/interface.css, interface.html, js/build.js, js/interface.js, translation.json, widget.json
Reverts Fliplet/fliplet-widget-login-data-source#124
=> Revert "Release 20240704"

js/build.js, js/interface.js
Reverts Fliplet/fliplet-widget-login-data-source#129
=> Revert "ID-4531 [FIX] Fixes for checking the correct plan"

build.html, css/interface.css, interface.html, js/build.js, js/interface.js, translation.json, widget.json
- Free and Public apps require a "Create account" screen to be configured
- https://weboo.atlassian.net/browse/ID-4584
- Related to: https://weboo.atlassian.net/browse/ID-4531
=> Release 20240709

build.html, css/build.css, interface.html, js/build.js, js/interface.js, translation.json
New setting for Show/Hide password
https://weboo.atlassian.net/browse/ID-4558
=> Release 20240709-3

build.html, translation.json
- Removes the translation instruction from the signup button label
https://weboo.atlassian.net/browse/PS-243
=> Release 20240909
